### ISSUE TITLE
Authorization server well-known configuration location is expected to be '/.well-known/oauth-authorization-server'

### ISSUE THREAD

**Issue by ydanneg** [open-eid/eudi-qeaa-as-mock#1]
Current implementation:  `/.well-known/openid-configuration`
Expected: `/.well-known/oauth-authorization-server`

Ref: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-11.2.3-2.2

**Comment by aarmam** [comment]
Agreed as suggested that /.well-known/openid-configuration is kept for compatibility as [RFC 8414](https://www.rfc-editor.org/rfc/rfc8414.html#section-3) accepts both.
