### ISSUE TITLE
Incorrect DeviceAuthentication's sessionTranscript format

### ISSUE THREAD

**Issue by ydanneg** [open-eid/eudi-qeaa-as-mock#8]
According to ISO/IEC 18013-5:2021 and your [own documentation](https://github.com/open-eid/eudi-qeaa-doc/blob/master/eudi-qeaa-issuer.md#mdl-presentation) `sessionTranscript` structure is an `array` type containing following elements:

Element | Description | Encoding
-- | -- | --
DeviceEngagementBytes | It MUST be set to null. | array
EReaderKeyBytes | It MUST be set to null. | null
Handover | It MUST be set to OpenID4VPHandover structure. | array

But current implementation have the wrong structure that contains only Handover element:
https://github.com/open-eid/eudi-qeaa-as-mock/blob/9ca403d2b38662cd703d900f2640c5e5246de981/src/main/java/ee/ria/eudi/qeaa/as/util/MDocUtil.java#L88-L89

**Comment by aarmam** [comment]
Related issue open-eid/eudi-qeaa-wallet-mock#5
